{{- if .Values.enablegkenginxingress -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gabs-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /java
        pathType: Prefix
        backend:
          service:
            name: {{ include "java-k8s-ccm-autostopping.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}